name: Pull request checks

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: robojackets/robocup-software:foxy
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install some dependencies
        run: "sudo ./util/ubuntu-setup --yes"

      - name: Run clang-format
        run:
          echo "::add-matcher::clang-format.json"
          make checkstyle-lines
          echo "::remove-matcher owner=clang-format::"
        if: always()

      - name: Build
        run: |
          echo "::add-matcher::clang.json"
          source /opt/ros/foxy/setup.bash
          source install/setup.bash
          make all
          echo "::remove-matcher owner=clang::"
        if: always()

      - name: Run clang-tidy
        run: |
          echo "::add-matcher::clang-tidy.json"
          source /opt/ros/foxy/setup.bash
          source install/setup.bash
          DIFFBRANCH=$GITHUB_REF make checktidy-lines
          echo "::remove-matcher owner=clang-tidy::"
        if: always()

      - name: Run mypy
        run: |
          echo "::add-matcher::mypy.json"
          source /opt/ros/foxy/setup.bash
          source install/setup.bash
          mypy --ignore-missing-imports rj_gameplay/
          echo "::remove-matcher owner=mypy::"
        if: always()

      - name: Run pylint
        run: |
          echo "::add-matcher::pylint.json"
          source /opt/ros/foxy/setup.bash
          source install/setup.bash
          pylint rj_gameplay/rj_gameplay rj_gameplay/stp
          echo "::remove-matcher owner=pylint-error::"
          echo "::remove-matcher owner=pylint-warning::"
        if: always()
